services:
  db:
    image: mysql:8.0
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -uroot -ppassword
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: web
    command: >
      bash -c "
      echo 'Waiting for MySQL...';
      until mysqladmin ping -h db -uroot -ppassword --silent; do
      sleep 1;
      done;
      echo 'MySQL is up!';
      bundle install &&
      bundle exec rails db:prepare &&
      rm -f tmp/pids/server.pid &&
      ./bin/dev
      "
    tty: true
    stdin_open: true
    volumes:
      - .:/myapp
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/myapp/node_modules
    environment:
      TZ: Asia/Tokyo
      SECRET_KEY_BASE: ab1d03af2bd3d9bdbf817c89f437b804c5a340cdcc4855d0e2b1626ed3fd6ba8971af5b4f15af7babfe73354f51ab4be7d4181ed0e7312cfa1e90e5c23d0540a
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome

  chrome:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - 4444:4444

volumes:
  mysql_data:
  bundle_data:
  node_modules: